title: Scot Carpenter
logo: /images/logo_circle.png
description: "<br>Check out my <a href='Elbert_Scot_Carpenter_Resume.pdf'>Resume</a> and <a href='https://www.linkedin.com/in/scot-carpenter-5882b92ab/'>LinkedIn</a>"
theme: jekyll-theme-minimal
